const FooterByMe = () => {
  return (
    <div className="w-full">
      {" "}
      <footer className="text-center py-3 bg-gray-300 w-full flex flex-col gap-2">
        <div className="flex justify-evenly items-center">
          <h1 className="text-gray-600 text-md">
            Made with ❤️ by{" "}
            <a
              href="https://github.com/jyotishankar04"
              className="text-indigo-500 hover:underline"
              target="_blank"
            >
              Jyotishankar Patra (Dev uvam)
            </a>
          </h1>
          <p className="text-gray-600 text-sm">
            Copyright &copy; 2025 devsuvam.xyz All rights reserved
          </p>
        </div>

        <p className="text-gray-600 text-sm">
          ⚠️ Disclaimer: This quiz is generated by AI technology. While we
          strive for accuracy, please be aware that errors may occur. Always
          verify answers independently. Thank you for your understanding!
        </p>
      </footer>
    </div>
  );
};

export default FooterByMe;
